feat: update actor_name assignment in decorator
Bogdanp/dramatiq pull request #641
Opened 2024-07-16 09:09 UTC by z0z0r4

Close https://github.com/Bogdanp/dramatiq/issues/640

2024-07-16 11:10 UTC, Bogdanp commented
This isn't the right approach, since it would be a breaking change to any currently-deployed code. I would prefer it if we checked for duplicate actor names and raised an error instead.

2024-07-16 14:10 UTC, z0z0r4 commented
Indeed, I think checking for duplicate actor_name is necessary. But at the same time, it is reasonable to change the default value. We should support functions decorated with the same function name by default, right? This should also be a design mistake.

2024-07-16 14:15 UTC, Bogdanp commented
I think it's more nuanced than a plain design mistake. At least, I remember thinking about this quite a bit when I made the original decision to use `__name__`. For example, even if we used `__qualname__` here, renaming the module in which an actor is defined would then potentially lead to a production bug (actors are looked up by name, and messages already enqueued for `mod1.foo` would not be able to find `mod2.foo`). Using `__qualname__` now is out of the question since it would break users' code for the same reason. So, the only good option is to keep using `__name__` and to error when there are duplicates.

2024-07-16 14:41 UTC, z0z0r4 commented
> actors are looked up by name, and messages already enqueued for mod1.foo would not be able to find mod2.foo

Will the production environment keep the queue unemptied and update dramatiq? I don't think so, but there is no evidence.

I will keep this pr until I open another to add the exception you said.

2024-07-27 00:04 UTC, z0z0r4 commented
@Bogdanp fixed

2024-08-06 06:03 UTC, Bogdanp requested changes

2024-08-06 06:03 UTC, Bogdanp commented on dramatiq/actor.py
> +        actor_name = actor_name or fn.__qualname__
This change shouldn't be here, no?

2024-08-06 14:20 UTC, z0z0r4 commented on dramatiq/actor.py
> +        actor_name = actor_name or fn.__qualname__
yeee, sorry

2024-08-06 14:22 UTC, z0z0r4 commented
fixed

2024-08-06 14:32 UTC, merged